language: java
jdk:
  - openjdk11

branches:
  only:
    - master
    - dev

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean :api-server:build"

before_install:
  - chmod +x gradlew
