language: java
jdk:
  - openjdk11

branches:
  only:
    - master
    - dev

cache:
  directories:
    - $HOME/.gradle

before_install:
  - chmod +x gradlew

script:
  - ./gradlew clean :app:api-service:build

install: true