real
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spg?serverTimezone=UTC
    username: root
    password: root

  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100

server:
  port: 80